### PR TITLE
Ignore .ghci files while querying project GHC

### LINKED ISSUE #336: Ignore `.ghci` files
If there is a `.ghci` file with the following contents
```
:set +t
```

then the command:
```sh
> cabal v2-exec ghc -v0 -- -package-env=- -e "System.Environment.getExecutablePath >>= putStrLn"
/home/hugin/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/bin/ghc
it :: ()
```

adds unexpected output.

Solution: ignore .ghci files

### PR DESCRIPTION
**Pull request by fendor**
closes #336

### CODE REVIEW

**Review by hasufell — APPROVED** [review]

File: src/HIE/Bios/Cradle.hs [hunk 1]
```diff
@@ -648,7 +648,10 @@ cabalGhcDirs :: FilePath -> CradleLoadResultT IO (FilePath, FilePath)
 cabalGhcDirs workDir = do
   libdir <- readProcessWithCwd_ workDir  "cabal" ["exec", "-v0", "--", "ghc", "--print-libdir"] ""
   exe <- readProcessWithCwd_ workDir  "cabal"
-      ["exec", "-v0", "--", "ghc", "-package-env=-", "-e", "do e <- System.Environment.getExecutablePath ; System.IO.putStr e"] ""
+      [ "exec", "-v0", "--" , "ghc", "-package-env=-", "-ignore-dot-ghci", "-e"
+      , "do e <- System.Environment.getExecutablePath ; System.IO.putStr e"
```
Comment (hasufell) [inline src/HIE/Bios/Cradle.hs:652]:
```suggestion
      , "Control.Monad.join (Control.Monad.fmap System.IO.putStr (System.Environment.getExecutablePath))"
```

Fix when `RebindableSyntax` is enabled.

File: src/HIE/Bios/Cradle.hs [hunk 2]
```diff
@@ -648,7 +648,10 @@ cabalGhcDirs :: FilePath -> CradleLoadResultT IO (FilePath, FilePath)
 cabalGhcDirs workDir = do
   libdir <- readProcessWithCwd_ workDir  "cabal" ["exec", "-v0", "--", "ghc", "--print-libdir"] ""
   exe <- readProcessWithCwd_ workDir  "cabal"
-      ["exec", "-v0", "--", "ghc", "-package-env=-", "-e", "do e <- System.Environment.getExecutablePath ; System.IO.putStr e"] ""
+      [ "exec", "-v0", "--" , "ghc", "-package-env=-", "-ignore-dot-ghci", "-e"
```
Comment (hasufell) [inline src/HIE/Bios/Cradle.hs:651]:
```suggestion
      -- DON'T TOUCH THIS CODE
      [ "exec", "-v0", "--" , "ghc", "-package-env=-", "-ignore-dot-ghci", "-e"
```

File: src/HIE/Bios/Cradle.hs (hunk 1 above)
Comment (fendor) [reply src/HIE/Bios/Cradle.hs]: Thanks!

**Review by wz1000 — APPROVED** [review]
